service: try-service-worker

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  profile: my
  stage: v1
  cfLogs: true

functions:
  hello:
    handler: handler.hello
    timeout: 6
    memorySize: 128
    events:
      - http:
          path: tests/cache
          method: get
          integration: lambda
          cors:
            origins:
              - '*'
          response:
            headers:
              Content-Type: "'application/json;charset=UTF-8'"
